apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /apps/demo/
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  destination:
    namespace: argocd
    name: in-cluster
  source:
    helm:
      valueFiles:
        - values.yaml
    # ✏️ Your repository URL
    repoURL: https://github.com/edix9/training-argocd.git
    path: apps/demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
