apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: demo
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`demo-alexandreh.playground.padok.cloud`)
    kind: Rule
    services:
    - name: demo
      port: 80
