apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: demo
spec:
  entryPoints:
    - web
  routes:
  {{- if .Values.preview.enabled }}
  - match: Host(`{{ .Values.ingressRoute.hostname }}`) && Headers(`{{ .Values.preview.header.name }}`, `{{ .Values.preview.header.value }}`)
  {{- else }}
  - match: Host(`{{ .Values.hosts }}`)
    kind: Rule
    services:
    - name: demo
      port: 80
  {{- end }}
